### ISSUE TITLE
Favicon not found in posts

### ISSUE THREAD

**Issue by carlcorder** [huangyz0918/moving#17]
I noticed that when I run a `jekyll serve` and navigate to a post I see the following error in my console:

```
ERROR '../favicon.ico' not found
```

Which is why the favicon doesn't show up on your posts. For example http://huangyz.name/moving/misc/2019/08/24/love-xinhai.html

Perhaps this is intentional?

**Comment by huangyz0918** [comment]
Thanks @carlcorder, I believe it is a bug, will fix soon.
