### ISSUE TITLE
Code highlighting missing color

### ISSUE THREAD

**Issue by carlcorder** [huangyz0918/moving#22]
When I run `jekyll serve` locally, code highlighting has color. After changing `theme: moving` to `remote_theme: huangyz0918/moving` and publishing to GitHub pages, the code syntax no longer has color.

* repo: https://github.com/carlcorder/carlcorder.dev/tree/gh-pages
* site: https://carlcorder.dev/
* code highlighting: https://carlcorder.dev/deep/learning/2019/08/29/hackathon-1.html

**Comment by huangyz0918** [comment]
I think this issue has been resolved. I will publish a new version and you @carlcorder can update with your blog. In case of missing something, is pull #21 fix this issue @luhc228 ？
