### ISSUE TITLE
CSS doesn't work when using theme via gem

### ISSUE THREAD

**Issue by robacarp** [huangyz0918/moving#24]
Following the installation instructions in the Readme at "Add Moving to an Existing Blog", the CSS doesn't work:

![image](https://user-images.githubusercontent.com/208647/65298259-0cb6eb80-db28-11e9-8fe0-3f0ce43e410d.png)

I'm not sure if this is a documentation bug or a packaging bug. A workaround is:

- make sure `gem "sassc"` is in your gemfile
- create a file at `project_root/assets/css/main.scss` with this content:

```scss
---
---

@import "moving";
```

**Comment by euyuil** [comment]
The workaround above resolves the not-found problem for main.css. The agate.css is still not found.

**Comment by huangyz0918** [comment]
@luhc228 I think it's a good chance to learn how to package a ruby gem, do you have interest to file a PR for that? It's a packaging issue, you can checkout the `moving.gemspec` and include `assets` in the packing path. 

BTW, help me to remove the `.DS_Store` in `assets`, thanks @luhc228  :P

**Comment by huangyz0918** [comment]
And thanks for testing about that @robacarp , we will fix this issue soon.

**Comment by huangyz0918** [comment]
I think version 0.3.4 has fixed this issue, please help me test and close this issue if it works. 
Thanks.

**Comment by thetinkeringtypist** [comment]
Version 0.3.4 did not resolve this issue for me.

**Comment by EmmettHan** [comment]
did it solved? i still encounter this question now.
