### ISSUE TITLE
Post List Wrapping

### ISSUE THREAD

**Issue by aleemb** [huangyz0918/moving#26]
The Post List css doesn't wrap correctly.

![image](https://user-images.githubusercontent.com/46616/65326086-15f89480-dbca-11e9-9681-9aef01bcf09c.png)

The following is hacky but it shows how it can be fixed via flex (similar to YinYang theme):

```
/* home: post list */
.post-list ul {
	margin-left: 0;
}
.post-list ul li {
	display: flex;
}
.post-meta {
	min-width: 80px;
	font-size: 21.6px;
}
```

**Comment by huangyz0918** [comment]
I think this proposal is great, can you @aleemb  file a PR for that?  Thanks a lot.
